name: Deploy to Live Server

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files with rsync
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude 'package-lock.json' \
            --exclude 'release.sh' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            vemamuwo@sl1702.web.hostpoint.ch:/home/vemamuwo/www/yagwud.com/content/themes/yagwud/